### ISSUE TITLE
List items not showing

### ISSUE THREAD

**Issue by geramirez** [CTOpenData/data-sharing-playbook#44]
For some reason, the layon.css file suppresses the list item numbers. Is there a way we can fix this.

![image](https://user-images.githubusercontent.com/4596845/76541496-afa24f80-6451-11ea-9e12-e68ae6be1b92.png)

![image](https://user-images.githubusercontent.com/4596845/76541471-a5805100-6451-11ea-8568-c31a265b37d0.png)

**Comment by matthewcrist** [comment]
Updated the underlying library with OL styling support.
